# Generated by Django 5.2.13 on 2026-09-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbuilder', '0001_initial'),
        ('ingest', '0007_document_body_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='+', to='ingest.document'),
        ),
    ]
