# Generated by Django 5.2.13 on 2026-08-29 18:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0004_document_embedding_document_embedding_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField(blank=True, help_text='系統自製摘要，非新聞原文')),
                ('current_status_text', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('candidate', '候選（自動偵測產生）'), ('draft', '草稿（待審核）'), ('active', '追蹤中'), ('dormant', '沉寂（新聞停報，官方源續查）'), ('closed', '已結案'), ('rejected', '審核駁回')], db_index=True, default='candidate', max_length=16)),
                ('visibility', models.CharField(choices=[('private', '未公開'), ('public', '已公開')], db_index=True, default='private', max_length=16)),
                ('domain', models.CharField(choices=[('judicial', '司法案件'), ('corruption', '政商弊案'), ('generic', '其他')], default='generic', max_length=16)),
                ('risk_tier', models.CharField(choices=[('high', '高（具名自然人且未判決確定）'), ('medium', '中（法人／機關，或已判決確定）'), ('low', '低（無指名對象）')], default='medium', help_text='由抽取結果自動判定，不由人工指定（規格 §4.3.1）', max_length=8)),
                ('core_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('case_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('last_progress_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_key_date', models.DateField(blank=True, help_text='下次開庭或關鍵期日', null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'ordering': ['-last_progress_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-last_progress_at'], name='event_status_prog'), models.Index(fields=['visibility', 'status'], name='event_vis_status')],
            },
        ),
        migrations.CreateModel(
            name='EventAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('is_former_slug', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='events.event')),
            ],
            options={
                'verbose_name': '事件別名',
                'verbose_name_plural': '事件別名',
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('method', models.CharField(choices=[('identifier', '識別碼精確比對'), ('llm', 'LLM 判定'), ('manual', '人工指定'), ('import', '標註集匯入')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='ingest.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='events.event')),
            ],
            options={
                'verbose_name': '事件文件關聯',
                'verbose_name_plural': '事件文件關聯',
                'indexes': [models.Index(fields=['event', '-relevance_score'], name='evdoc_event_score')],
                'unique_together': {('event', 'document')},
            },
        ),
    ]
