# Generated by Django 5.2.13 on 2026-08-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMergeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_slug', models.SlugField(allow_unicode=True, max_length=128)),
                ('source_title', models.CharField(max_length=256)),
                ('document_count', models.PositiveIntegerField(default=0, help_text='合併時由來源事件轉移過去的文件數')),
                ('reason', models.TextField(blank=True)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_logs_as_source', to='events.event')),
                ('target_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_logs_as_target', to='events.event')),
            ],
            options={
                'verbose_name': '事件合併紀錄',
                'verbose_name_plural': '事件合併紀錄',
                'ordering': ['-merged_at'],
            },
        ),
    ]
