# Generated by Django 5.2.13 on 2026-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmergelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='method',
            field=models.CharField(choices=[('identifier', '識別碼精確比對'), ('llm', 'LLM 判定'), ('manual', '人工指定'), ('import', '標註集匯入'), ('cluster', '自動叢集（新事件候選）')], max_length=16),
        ),
    ]
