# Generated by Django 5.2.13 on 2026-08-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventdocument_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_official_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
