# Generated by Django 5.2.13 on 2026-08-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0002_document_relevance_signals_document_relevant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_kind', models.CharField(db_index=True, max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(db_index=True, max_length=32)),
                ('succeeded', models.BooleanField(db_index=True, default=True)),
                ('error', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True, help_text='解析失敗時保留原始回應供除錯')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='ingest.document')),
            ],
            options={
                'verbose_name': 'L1 抽取結果',
                'verbose_name_plural': 'L1 抽取結果',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='extraction_doc_time'), models.Index(fields=['schema_kind', 'prompt_version'], name='extraction_kind_version')],
            },
        ),
    ]
