# Generated by Django 5.2.13 on 2026-08-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_last_official_check_at'),
        ('ingest', '0004_document_embedding_document_embedding_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('extraction', 'L1 結構化抽取'), ('relevance', '相關性判定'), ('event_linking', 'L3 事件歸屬'), ('event_summary', 'L3 事件摘要'), ('causal', 'L4 因果推理'), ('narrative', 'L4 敘事生成'), ('wording_check', '措辭檢查'), ('other', '其他')], max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(max_length=32)),
                ('input_summary', models.TextField(blank=True, help_text='輸入摘要，非完整原文')),
                ('output_text', models.TextField(blank=True, help_text='模型原始輸出，後處理前')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '生成紀錄',
                'verbose_name_plural': '生成紀錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField(blank=True, help_text='本節點所述事實的發生日期，未載明則留空', null=True)),
                ('summary', models.CharField(max_length=200)),
                ('citation_excerpt', models.TextField(blank=True, help_text='引用段落，供人工核對')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citation_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeline_citations', to='ingest.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_nodes', to='events.event')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='timeline.generationlog')),
            ],
            options={
                'verbose_name': '時間線節點',
                'verbose_name_plural': '時間線節點',
                'ordering': ['occurred_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CausalEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('stated', '報導明述'), ('inferred', '系統推論')], max_length=8)),
                ('citation_excerpt', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citation_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='causal_citations', to='ingest.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_edges', to='events.event')),
                ('generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causal_edges', to='timeline.generationlog')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='timeline.timelinenode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='timeline.timelinenode')),
            ],
            options={
                'verbose_name': '因果邊',
                'verbose_name_plural': '因果邊',
            },
        ),
        migrations.AddIndex(
            model_name='timelinenode',
            index=models.Index(fields=['event', 'occurred_on'], name='tlnode_event_date'),
        ),
        migrations.AddIndex(
            model_name='causaledge',
            index=models.Index(fields=['event'], name='causaledge_event'),
        ),
        migrations.AddIndex(
            model_name='causaledge',
            index=models.Index(fields=['from_node'], name='causaledge_from'),
        ),
        migrations.AddConstraint(
            model_name='causaledge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'stated'), _negated=True), ('citation_document__isnull', False), _connector='OR'), name='causal_stated_requires_citation'),
        ),
        migrations.AddConstraint(
            model_name='causaledge',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'inferred'), _negated=True), ('confidence__isnull', False), _connector='OR'), name='causal_inferred_requires_confidence'),
        ),
        migrations.AddConstraint(
            model_name='causaledge',
            constraint=models.CheckConstraint(condition=models.Q(('from_node', models.F('to_node')), _negated=True), name='causal_edge_no_self_loop'),
        ),
    ]
