# Generated by Django 5.2.13 on 2026-08-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='causaledge',
            name='publicly_visible',
            field=models.BooleanField(default=False),
        ),
    ]
