# Generated by Django 5.2.13 on 2026-08-29 16:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('purpose', models.CharField(choices=[('extraction', 'L1 結構化抽取'), ('relevance', '相關性判定'), ('event_linking', 'L3 事件歸屬'), ('event_summary', 'L3 事件摘要'), ('causal', 'L4 因果推理'), ('narrative', 'L4 敘事生成'), ('wording_check', '措辭檢查'), ('other', '其他')], db_index=True, default='other', max_length=32)),
                ('task_name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('cached_input_tokens', models.IntegerField(default=0)),
                ('uncached_input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=12)),
                ('cost_ntd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('usd_to_ntd', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('peak', models.BooleanField(default=False, help_text='是否為尖峰時段（離峰價格減半）')),
                ('duration_ms', models.IntegerField(default=0)),
                ('succeeded', models.BooleanField(db_index=True, default=True)),
                ('error', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usages', to='ingest.document')),
            ],
            options={
                'verbose_name': 'LLM 用量',
                'verbose_name_plural': 'LLM 用量',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'purpose'], name='llmusage_time_purpose'), models.Index(fields=['model', '-created_at'], name='llmusage_model_time')],
            },
        ),
    ]
