# Generated by Django 5.2.13 on 2026-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmBudgetGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('amount_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('granted_by', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'LLM 額度追加',
                'verbose_name_plural': 'LLM 額度追加',
                'ordering': ['-created_at'],
            },
        ),
    ]
