# Generated by Django 5.2.13 on 2026-08-29 13:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('news_rss', '新聞 RSS'), ('news_scrape', '新聞爬蟲'), ('judicial_api', '司法院裁判書 API'), ('ly_api', '立法院開放資料'), ('cy_scrape', '監察院爬蟲'), ('pcc_dataset', '政府採購網資料集')], max_length=32)),
                ('base_url', models.URLField(max_length=512)),
                ('feed_url', models.URLField(blank=True, max_length=512)),
                ('content_class', models.CharField(choices=[('copyrighted', '受著作權保護（僅內部）'), ('public_record', '公文（可公開）')], default='copyrighted', help_text='此來源產出的文件預設歸類；決定全文能否公開', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=60)),
                ('service_window_start_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('service_window_end_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='來源自身的識別碼，如裁判書的 JID', max_length=128)),
                ('title', models.CharField(max_length=512)),
                ('raw_body', models.TextField(blank=True, help_text='原始全文。content_class=copyrighted 時永不對外序列化。')),
                ('content_class', models.CharField(choices=[('copyrighted', '受著作權保護（僅內部）'), ('public_record', '公文（可公開）')], max_length=32)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('simhash', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('search_text', models.TextField(blank=True, editable=False)),
                ('search_vector', models.GeneratedField(db_persist=True, expression=models.Func(models.Value('simple'), models.F('search_text'), function='to_tsvector'), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('canonical_of', models.ForeignKey(blank=True, help_text='若本文為轉載，指向首發版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprints', to='ingest.document')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='ingest.source')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='document_search_gin'), models.Index(fields=['source', '-published_at'], name='document_source_pub'), models.Index(fields=['content_class'], name='document_content_class')],
            },
        ),
    ]
