# Generated by Django 5.2.13 on 2026-08-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='relevance_signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='document',
            name='relevant',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
