# Generated by Django 5.2.13 on 2026-08-29 18:18

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_document_relevance_signals_document_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='case_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='正規化後的裁判書案號，如「111年度金重訴字第123號」', size=None),
        ),
        migrations.AddField(
            model_name='document',
            name='tax_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, help_text='通過檢查碼驗證的統一編號', size=None),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['case_numbers'], name='document_case_gin'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tax_ids'], name='document_taxid_gin'),
        ),
    ]
