# Generated by Django 5.2.13 on 2026-08-29 18:40

import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_document_case_numbers_document_tax_ids_and_more'),
    ]

    operations = [
        # extension 必須先於 halfvec 欄位建立。測試資料庫每次重建、
        # 不繼承主庫的 extension，少了這一步所有向量測試都會失敗，
        # 而錯誤訊息「type "halfvec" does not exist」指向型別，
        # 不會讓人立刻想到是 extension 沒裝。
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="-- 刻意不移除：其他資料表可能仍依賴",
        ),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_version',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='document',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='document_embedding_hnsw', opclasses=['halfvec_cosine_ops']),
        ),
    ]
