# Generated by Django 5.2.13 on 2026-08-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_document_embedding_document_embedding_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('login_url', models.URLField(max_length=512)),
                ('cookie_header', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('expected_valid_hours', models.PositiveIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '外部平台登入 session',
                'verbose_name_plural': '外部平台登入 session',
            },
        ),
    ]
