# Generated by Django 5.2.13 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_externalsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='archive_earliest_on_site',
            field=models.DateField(blank=True, help_text='站台歷史清單實測可回溯的最早日期', null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_cursor',
            field=models.TextField(blank=True, help_text='回補進度（日期、頁碼或 offset 的 JSON）'),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_status',
            field=models.CharField(default='idle', help_text='idle / running / done / error', max_length=16),
        ),
        migrations.AddField(
            model_name='source',
            name='historical_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
