# Generated by Django 5.2.13 on 2026-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_source_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='body_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
